/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.kairos.webots.polycreate.controler;

import com.yakindu.core.IStatemachine;
import com.yakindu.core.ITimed;
import com.yakindu.core.ITimerService;
import com.yakindu.core.rx.Observable;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class Statechart2 implements IStatemachine, ITimed {
	public enum State {
		MOVE_ROBOT_IS_RUNNING,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_TURNING,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEBACK,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEFRONT,
		MOVE_ROBOT_IS_RUNNING_RÉGION__GAP_DOWN,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_MOVEBACK,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_GRIP,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_PAUSE_,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_TURNROUND,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_FACEOBJECT,
		MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_SAVEPOSITION_SAVEPOSITION,
		MOVE_ROBOT_IS_RUNNING_RÉGION__BLOCAGE,
		MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL,
		MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_STOP,
		MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_BLOCK,
		PASSIVE_WAIT_WAIT,
		CHECK_CHECK,
		$NULLSTATE$
	};
	
	private final State[] stateVector = new State[4];
	
	private ITimerService timerService;
	
	private final boolean[] timeEvents = new boolean[4];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		synchronized(Statechart2.this) {
			return isExecuting;
		}
	}
	
	protected void setIsExecuting(boolean value) {
		synchronized(Statechart2.this) {
			this.isExecuting = value;
		}
	}
	private long stateConfVectorPosition;
	
	protected long getStateConfVectorPosition() {
		synchronized(Statechart2.this) {
			return stateConfVectorPosition;
		}
	}
	
	protected void setStateConfVectorPosition(long value) {
		synchronized(Statechart2.this) {
			this.stateConfVectorPosition = value;
		}
	}
	public Statechart2() {
		for (int i = 0; i < 4; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		
		isExecuting = false;
	}
	
	public synchronized void enter() {
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		
		enterSequence_move_default();
		enterSequence_passive_wait_default();
		enterSequence_check_default();
		isExecuting = false;
	}
	
	public synchronized void exit() {
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		
		exitSequence_move();
		exitSequence_passive_wait();
		exitSequence_check();
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$||stateVector[1] != State.$NULLSTATE$||stateVector[2] != State.$NULLSTATE$||stateVector[3] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	private void clearInEvents() {
		thereIsAnObstacle = false;
		thereIsNoObstacle = false;
		thereIsAFrontObstacle = false;
		thereIsAVirtualWall = false;
		thereIsAnObjectFront = false;
		thereIsNoVirtualWall = false;
		thereIsAGapDown = false;
		thereIsNoObstacleFront = false;
		thereIsnoGap = false;
		theGripIsClose = false;
		theGripIsNotClose = false;
		theObjectIsGrip = false;
		objectGrip = false;
		robotIsBlocked = false;
		isFacingTheObject = false;
		timeEvents[0] = false;
		timeEvents[1] = false;
		timeEvents[2] = false;
		timeEvents[3] = false;
	}
	
	private void microStep() {
		long transitioned = -1;
		
		stateConfVectorPosition = 0;
		
		switch (stateVector[0]) {
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_TURNING:
			transitioned = move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning_react(transitioned);
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEBACK:
			transitioned = move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveBack_react(transitioned);
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEFRONT:
			transitioned = move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveFront_react(transitioned);
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__GAP_DOWN:
			transitioned = move_robot_is_running_R_gion__gap_down_react(transitioned);
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_MOVEBACK:
			transitioned = move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_moveBack_react(transitioned);
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_GRIP:
			transitioned = move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_grip_react(transitioned);
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_PAUSE_:
			transitioned = move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_pause__react(transitioned);
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_TURNROUND:
			transitioned = move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_turnRound_react(transitioned);
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_FACEOBJECT:
			transitioned = move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_faceobject_react(transitioned);
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__BLOCAGE:
			transitioned = move_robot_is_running_R_gion__blocage_react(transitioned);
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_STOP:
			transitioned = move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_stop_react(transitioned);
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_BLOCK:
			transitioned = move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_block_react(transitioned);
			break;
		default:
			break;
		}
		
		if (getStateConfVectorPosition()<1) {
			switch (stateVector[1]) {
			case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_SAVEPOSITION_SAVEPOSITION:
				transitioned = move_robot_is_running_R_gion__robots_and_object_savePosition_savePosition_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<2) {
			switch (stateVector[2]) {
			case PASSIVE_WAIT_WAIT:
				transitioned = passive_wait_wait_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<3) {
			switch (stateVector[3]) {
			case CHECK_CHECK:
				transitioned = check_check_react(transitioned);
				break;
			default:
				break;
			}
		}
	}
	
	private void runCycle() {
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		
		nextEvent();
		do { 
			microStep();
			
			clearInEvents();
			
			nextEvent();
		} while (((((((((((((((((((thereIsAnObstacle || thereIsNoObstacle) || thereIsAFrontObstacle) || thereIsAVirtualWall) || thereIsAnObjectFront) || thereIsNoVirtualWall) || thereIsAGapDown) || thereIsNoObstacleFront) || thereIsnoGap) || theGripIsClose) || theGripIsNotClose) || theObjectIsGrip) || objectGrip) || robotIsBlocked) || isFacingTheObject) || timeEvents[0]) || timeEvents[1]) || timeEvents[2]) || timeEvents[3]));
		
		isExecuting = false;
	}
	
	protected void nextEvent() {
		if(!inEventQueue.isEmpty()) {
			inEventQueue.poll().run();
			return;
		}
	}
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case MOVE_ROBOT_IS_RUNNING:
			return stateVector[0].ordinal() >= State.
					MOVE_ROBOT_IS_RUNNING.ordinal()&& stateVector[0].ordinal() <= State.MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_BLOCK.ordinal();
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE:
			return stateVector[0].ordinal() >= State.
					MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE.ordinal()&& stateVector[0].ordinal() <= State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEFRONT.ordinal();
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_TURNING:
			return stateVector[0] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_TURNING;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES:
			return stateVector[0].ordinal() >= State.
					MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES.ordinal()&& stateVector[0].ordinal() <= State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEFRONT.ordinal();
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEBACK:
			return stateVector[0] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEBACK;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEFRONT:
			return stateVector[0] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEFRONT;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__GAP_DOWN:
			return stateVector[0] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__GAP_DOWN;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT:
			return stateVector[0].ordinal() >= State.
					MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT.ordinal()&& stateVector[0].ordinal() <= State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_SAVEPOSITION_SAVEPOSITION.ordinal();
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP:
			return stateVector[0].ordinal() >= State.
					MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP.ordinal()&& stateVector[0].ordinal() <= State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_FACEOBJECT.ordinal();
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_MOVEBACK:
			return stateVector[0] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_MOVEBACK;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_GRIP:
			return stateVector[0] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_GRIP;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_PAUSE_:
			return stateVector[0] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_PAUSE_;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_TURNROUND:
			return stateVector[0] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_TURNROUND;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_FACEOBJECT:
			return stateVector[0] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_FACEOBJECT;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_SAVEPOSITION_SAVEPOSITION:
			return stateVector[1] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_SAVEPOSITION_SAVEPOSITION;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__BLOCAGE:
			return stateVector[0] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__BLOCAGE;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL:
			return stateVector[0].ordinal() >= State.
					MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL.ordinal()&& stateVector[0].ordinal() <= State.MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_BLOCK.ordinal();
		case MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_STOP:
			return stateVector[0] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_STOP;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_BLOCK:
			return stateVector[0] == State.MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_BLOCK;
		case PASSIVE_WAIT_WAIT:
			return stateVector[2] == State.PASSIVE_WAIT_WAIT;
		case CHECK_CHECK:
			return stateVector[3] == State.CHECK_CHECK;
		default:
			return false;
		}
	}
	
	public synchronized void setTimerService(ITimerService timerService) {
		this.timerService = timerService;
	}
	
	public ITimerService getTimerService() {
		return timerService;
	}
	
	public synchronized void raiseTimeEvent(int eventID) {
		inEventQueue.add(() -> {
			timeEvents[eventID] = true;
		});
		runCycle();
	}
	
	
	private boolean thereIsAnObstacle;
	
	
	public void raiseThereIsAnObstacle() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				thereIsAnObstacle = true;
			});
			runCycle();
		}
	}
	
	private boolean thereIsNoObstacle;
	
	
	public void raiseThereIsNoObstacle() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				thereIsNoObstacle = true;
			});
			runCycle();
		}
	}
	
	private boolean thereIsAFrontObstacle;
	
	
	public void raiseThereIsAFrontObstacle() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				thereIsAFrontObstacle = true;
			});
			runCycle();
		}
	}
	
	private boolean thereIsAVirtualWall;
	
	
	public void raiseThereIsAVirtualWall() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				thereIsAVirtualWall = true;
			});
			runCycle();
		}
	}
	
	private boolean thereIsAnObjectFront;
	
	
	public void raiseThereIsAnObjectFront() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				thereIsAnObjectFront = true;
			});
			runCycle();
		}
	}
	
	private boolean thereIsNoVirtualWall;
	
	
	public void raiseThereIsNoVirtualWall() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				thereIsNoVirtualWall = true;
			});
			runCycle();
		}
	}
	
	private boolean thereIsAGapDown;
	
	
	public void raiseThereIsAGapDown() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				thereIsAGapDown = true;
			});
			runCycle();
		}
	}
	
	private boolean thereIsNoObstacleFront;
	
	
	public void raiseThereIsNoObstacleFront() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				thereIsNoObstacleFront = true;
			});
			runCycle();
		}
	}
	
	private boolean thereIsnoGap;
	
	
	public void raiseThereIsnoGap() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				thereIsnoGap = true;
			});
			runCycle();
		}
	}
	
	private boolean theGripIsClose;
	
	
	public void raiseTheGripIsClose() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				theGripIsClose = true;
			});
			runCycle();
		}
	}
	
	private boolean theGripIsNotClose;
	
	
	public void raiseTheGripIsNotClose() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				theGripIsNotClose = true;
			});
			runCycle();
		}
	}
	
	private boolean theObjectIsGrip;
	
	
	public void raiseTheObjectIsGrip() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				theObjectIsGrip = true;
			});
			runCycle();
		}
	}
	
	private boolean objectGrip;
	
	
	public void raiseObjectGrip() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				objectGrip = true;
			});
			runCycle();
		}
	}
	
	private boolean robotIsBlocked;
	
	
	public void raiseRobotIsBlocked() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				robotIsBlocked = true;
			});
			runCycle();
		}
	}
	
	private boolean isFacingTheObject;
	
	
	public void raiseIsFacingTheObject() {
		synchronized(Statechart2.this) {
			inEventQueue.add(() -> {
				isFacingTheObject = true;
			});
			runCycle();
		}
	}
	
	private boolean turn;
	
	
	protected void raiseTurn() {
		synchronized(Statechart2.this) {
			turn = true;
			turnObservable.next(null);
		}
	}
	
	private Observable<Void> turnObservable = new Observable<Void>();
	
	public Observable<Void> getTurn() {
		return turnObservable;
	}
	
	private boolean moveFront;
	
	
	protected void raiseMoveFront() {
		synchronized(Statechart2.this) {
			moveFront = true;
			moveFrontObservable.next(null);
		}
	}
	
	private Observable<Void> moveFrontObservable = new Observable<Void>();
	
	public Observable<Void> getMoveFront() {
		return moveFrontObservable;
	}
	
	private boolean check;
	
	
	protected void raiseCheck() {
		synchronized(Statechart2.this) {
			check = true;
			checkObservable.next(null);
		}
	}
	
	private Observable<Void> checkObservable = new Observable<Void>();
	
	public Observable<Void> getCheck() {
		return checkObservable;
	}
	
	private boolean moveBack;
	
	
	protected void raiseMoveBack() {
		synchronized(Statechart2.this) {
			moveBack = true;
			moveBackObservable.next(null);
		}
	}
	
	private Observable<Void> moveBackObservable = new Observable<Void>();
	
	public Observable<Void> getMoveBack() {
		return moveBackObservable;
	}
	
	private boolean fullTurn;
	
	
	protected void raiseFullTurn() {
		synchronized(Statechart2.this) {
			fullTurn = true;
			fullTurnObservable.next(null);
		}
	}
	
	private Observable<Void> fullTurnObservable = new Observable<Void>();
	
	public Observable<Void> getFullTurn() {
		return fullTurnObservable;
	}
	
	private boolean stop;
	
	
	protected void raiseStop() {
		synchronized(Statechart2.this) {
			stop = true;
			stopObservable.next(null);
		}
	}
	
	private Observable<Void> stopObservable = new Observable<Void>();
	
	public Observable<Void> getStop() {
		return stopObservable;
	}
	
	private boolean turnRound;
	
	
	protected void raiseTurnRound() {
		synchronized(Statechart2.this) {
			turnRound = true;
			turnRoundObservable.next(null);
		}
	}
	
	private Observable<Void> turnRoundObservable = new Observable<Void>();
	
	public Observable<Void> getTurnRound() {
		return turnRoundObservable;
	}
	
	private boolean grip;
	
	
	protected void raiseGrip() {
		synchronized(Statechart2.this) {
			grip = true;
			gripObservable.next(null);
		}
	}
	
	private Observable<Void> gripObservable = new Observable<Void>();
	
	public Observable<Void> getGrip() {
		return gripObservable;
	}
	
	private boolean doPW;
	
	
	protected void raiseDoPW() {
		synchronized(Statechart2.this) {
			doPW = true;
			doPWObservable.next(null);
		}
	}
	
	private Observable<Void> doPWObservable = new Observable<Void>();
	
	public Observable<Void> getDoPW() {
		return doPWObservable;
	}
	
	private boolean saveRobotPosition;
	
	
	protected void raiseSaveRobotPosition() {
		synchronized(Statechart2.this) {
			saveRobotPosition = true;
			saveRobotPositionObservable.next(null);
		}
	}
	
	private Observable<Void> saveRobotPositionObservable = new Observable<Void>();
	
	public Observable<Void> getSaveRobotPosition() {
		return saveRobotPositionObservable;
	}
	
	private boolean checkGripping;
	
	
	protected void raiseCheckGripping() {
		synchronized(Statechart2.this) {
			checkGripping = true;
			checkGrippingObservable.next(null);
		}
	}
	
	private Observable<Void> checkGrippingObservable = new Observable<Void>();
	
	public Observable<Void> getCheckGripping() {
		return checkGrippingObservable;
	}
	
	private boolean deblock;
	
	
	protected void raiseDeblock() {
		synchronized(Statechart2.this) {
			deblock = true;
			deblockObservable.next(null);
		}
	}
	
	private Observable<Void> deblockObservable = new Observable<Void>();
	
	public Observable<Void> getDeblock() {
		return deblockObservable;
	}
	
	private boolean faceObject;
	
	
	protected void raiseFaceObject() {
		synchronized(Statechart2.this) {
			faceObject = true;
			faceObjectObservable.next(null);
		}
	}
	
	private Observable<Void> faceObjectObservable = new Observable<Void>();
	
	public Observable<Void> getFaceObject() {
		return faceObjectObservable;
	}
	
	/* Entry action for state 'turning'. */
	private void entryAction_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning() {
		raiseTurn();
	}
	
	/* Entry action for state 'moveBack'. */
	private void entryAction_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveBack() {
		raiseMoveBack();
	}
	
	/* Entry action for state 'moveFront'. */
	private void entryAction_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveFront() {
		raiseMoveFront();
	}
	
	/* Entry action for state 'gap down'. */
	private void entryAction_move_robot_is_running_R_gion__gap_down() {
		raiseMoveBack();
	}
	
	/* Entry action for state 'moveBack'. */
	private void entryAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_moveBack() {
		raiseMoveBack();
	}
	
	/* Entry action for state 'grip'. */
	private void entryAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_grip() {
		timerService.setTimer(this, 0, (1 * 1000), false);
		
		raiseGrip();
	}
	
	/* Entry action for state 'pause '. */
	private void entryAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_pause_() {
		timerService.setTimer(this, 1, (450 * 1000), true);
		
		raiseStop();
	}
	
	/* Entry action for state 'turnRound'. */
	private void entryAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_turnRound() {
		raiseTurnRound();
	}
	
	/* Entry action for state 'faceobject'. */
	private void entryAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_faceobject() {
		raiseFaceObject();
	}
	
	/* Entry action for state 'blocage'. */
	private void entryAction_move_robot_is_running_R_gion__blocage() {
		raiseDeblock();
	}
	
	/* Entry action for state 'virtual stop'. */
	private void entryAction_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_stop() {
		raiseFullTurn();
	}
	
	/* Entry action for state 'virtual block'. */
	private void entryAction_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_block() {
		raiseTurnRound();
	}
	
	/* Entry action for state 'wait'. */
	private void entryAction_passive_wait_wait() {
		timerService.setTimer(this, 2, 300, true);
	}
	
	/* Entry action for state 'check'. */
	private void entryAction_check_check() {
		timerService.setTimer(this, 3, 200, true);
	}
	
	/* Exit action for state 'grip'. */
	private void exitAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_grip() {
		timerService.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'pause '. */
	private void exitAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_pause_() {
		timerService.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'wait'. */
	private void exitAction_passive_wait_wait() {
		timerService.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'check'. */
	private void exitAction_check_check() {
		timerService.unsetTimer(this, 3);
	}
	
	/* 'default' enter sequence for state robot is running */
	private void enterSequence_move_robot_is_running_default() {
		enterSequence_move_robot_is_running_R_gion__default();
	}
	
	/* 'default' enter sequence for state robot and obstacle */
	private void enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_default() {
		enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_default();
	}
	
	/* 'default' enter sequence for state turning */
	private void enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning_default() {
		entryAction_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning();
		stateVector[0] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_TURNING;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state moves */
	private void enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_default() {
		enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_default();
	}
	
	/* 'default' enter sequence for state moveBack */
	private void enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveBack_default() {
		entryAction_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveBack();
		stateVector[0] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEBACK;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state moveFront */
	private void enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveFront_default() {
		entryAction_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveFront();
		stateVector[0] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEFRONT;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state gap down */
	private void enterSequence_move_robot_is_running_R_gion__gap_down_default() {
		entryAction_move_robot_is_running_R_gion__gap_down();
		stateVector[0] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__GAP_DOWN;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state grip */
	private void enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_default() {
		enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_default();
	}
	
	/* 'default' enter sequence for state moveBack */
	private void enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_moveBack_default() {
		entryAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_moveBack();
		stateVector[0] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_MOVEBACK;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state grip */
	private void enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_grip_default() {
		entryAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_grip();
		stateVector[0] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_GRIP;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state pause  */
	private void enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_pause__default() {
		entryAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_pause_();
		stateVector[0] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_PAUSE_;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state turnRound */
	private void enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_turnRound_default() {
		entryAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_turnRound();
		stateVector[0] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_TURNROUND;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state faceobject */
	private void enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_faceobject_default() {
		entryAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_faceobject();
		stateVector[0] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_FACEOBJECT;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state savePosition */
	private void enterSequence_move_robot_is_running_R_gion__robots_and_object_savePosition_savePosition_default() {
		stateVector[1] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_SAVEPOSITION_SAVEPOSITION;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state blocage */
	private void enterSequence_move_robot_is_running_R_gion__blocage_default() {
		entryAction_move_robot_is_running_R_gion__blocage();
		stateVector[0] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__BLOCAGE;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state virtualWall */
	private void enterSequence_move_robot_is_running_R_gion__virtualWall_default() {
		enterSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_default();
	}
	
	/* 'default' enter sequence for state virtual stop */
	private void enterSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_stop_default() {
		entryAction_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_stop();
		stateVector[0] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_STOP;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state virtual block */
	private void enterSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_block_default() {
		entryAction_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_block();
		stateVector[0] = State.MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_BLOCK;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state wait */
	private void enterSequence_passive_wait_wait_default() {
		entryAction_passive_wait_wait();
		stateVector[2] = State.PASSIVE_WAIT_WAIT;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state check */
	private void enterSequence_check_check_default() {
		entryAction_check_check();
		stateVector[3] = State.CHECK_CHECK;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for region move */
	private void enterSequence_move_default() {
		react_move__entry_Default();
	}
	
	/* 'default' enter sequence for region Région  */
	private void enterSequence_move_robot_is_running_R_gion__default() {
		react_move_robot_is_running_R_gion___entry_Default();
	}
	
	/* 'default' enter sequence for region dodgeObstacle */
	private void enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_default() {
		react_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_default() {
		react_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_default() {
		react_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region savePosition */
	private void enterSequence_move_robot_is_running_R_gion__robots_and_object_savePosition_default() {
		react_move_robot_is_running_R_gion__robots_and_object_savePosition__entry_Default();
	}
	
	/* 'default' enter sequence for region do not cross a virtual wall */
	private void enterSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_default() {
		react_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall__entry_Default();
	}
	
	/* 'default' enter sequence for region passive_wait */
	private void enterSequence_passive_wait_default() {
		react_passive_wait__entry_Default();
	}
	
	/* 'default' enter sequence for region check */
	private void enterSequence_check_default() {
		react_check__entry_Default();
	}
	
	/* Default exit sequence for state robot and obstacle */
	private void exitSequence_move_robot_is_running_R_gion__robot_and_obstacle() {
		exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle();
	}
	
	/* Default exit sequence for state turning */
	private void exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state moves */
	private void exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves() {
		exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1();
	}
	
	/* Default exit sequence for state moveBack */
	private void exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveBack() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state moveFront */
	private void exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveFront() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state gap down */
	private void exitSequence_move_robot_is_running_R_gion__gap_down() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state robots and object */
	private void exitSequence_move_robot_is_running_R_gion__robots_and_object() {
		exitSequence_move_robot_is_running_R_gion__robots_and_object_r1();
		exitSequence_move_robot_is_running_R_gion__robots_and_object_savePosition();
	}
	
	/* Default exit sequence for state moveBack */
	private void exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_moveBack() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state grip */
	private void exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_grip() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
		
		exitAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_grip();
	}
	
	/* Default exit sequence for state pause  */
	private void exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_pause_() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
		
		exitAction_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_pause_();
	}
	
	/* Default exit sequence for state turnRound */
	private void exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_turnRound() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state faceobject */
	private void exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_faceobject() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state savePosition */
	private void exitSequence_move_robot_is_running_R_gion__robots_and_object_savePosition_savePosition() {
		stateVector[1] = State.$NULLSTATE$;
		stateConfVectorPosition = 1;
	}
	
	/* Default exit sequence for state blocage */
	private void exitSequence_move_robot_is_running_R_gion__blocage() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state virtualWall */
	private void exitSequence_move_robot_is_running_R_gion__virtualWall() {
		exitSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall();
	}
	
	/* Default exit sequence for state virtual stop */
	private void exitSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_stop() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state virtual block */
	private void exitSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_block() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state wait */
	private void exitSequence_passive_wait_wait() {
		stateVector[2] = State.$NULLSTATE$;
		stateConfVectorPosition = 2;
		
		exitAction_passive_wait_wait();
	}
	
	/* Default exit sequence for state check */
	private void exitSequence_check_check() {
		stateVector[3] = State.$NULLSTATE$;
		stateConfVectorPosition = 3;
		
		exitAction_check_check();
	}
	
	/* Default exit sequence for region move */
	private void exitSequence_move() {
		switch (stateVector[0]) {
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_TURNING:
			exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEBACK:
			exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveBack();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEFRONT:
			exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveFront();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__GAP_DOWN:
			exitSequence_move_robot_is_running_R_gion__gap_down();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_MOVEBACK:
			exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_moveBack();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_GRIP:
			exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_grip();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_PAUSE_:
			exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_pause_();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_TURNROUND:
			exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_turnRound();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_FACEOBJECT:
			exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_faceobject();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__BLOCAGE:
			exitSequence_move_robot_is_running_R_gion__blocage();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_STOP:
			exitSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_stop();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_BLOCK:
			exitSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_block();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_SAVEPOSITION_SAVEPOSITION:
			exitSequence_move_robot_is_running_R_gion__robots_and_object_savePosition_savePosition();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region dodgeObstacle */
	private void exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle() {
		switch (stateVector[0]) {
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_TURNING:
			exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEBACK:
			exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveBack();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEFRONT:
			exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveFront();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1() {
		switch (stateVector[0]) {
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEBACK:
			exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveBack();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOT_AND_OBSTACLE_DODGEOBSTACLE_MOVES_R1_MOVEFRONT:
			exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveFront();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_move_robot_is_running_R_gion__robots_and_object_r1() {
		switch (stateVector[0]) {
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_MOVEBACK:
			exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_moveBack();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_GRIP:
			exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_grip();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_PAUSE_:
			exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_pause_();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_TURNROUND:
			exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_turnRound();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_R1_GRIP_R1_FACEOBJECT:
			exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_faceobject();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region savePosition */
	private void exitSequence_move_robot_is_running_R_gion__robots_and_object_savePosition() {
		switch (stateVector[1]) {
		case MOVE_ROBOT_IS_RUNNING_RÉGION__ROBOTS_AND_OBJECT_SAVEPOSITION_SAVEPOSITION:
			exitSequence_move_robot_is_running_R_gion__robots_and_object_savePosition_savePosition();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region do not cross a virtual wall */
	private void exitSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall() {
		switch (stateVector[0]) {
		case MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_STOP:
			exitSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_stop();
			break;
		case MOVE_ROBOT_IS_RUNNING_RÉGION__VIRTUALWALL_DO_NOT_CROSS_A_VIRTUAL_WALL_VIRTUAL_BLOCK:
			exitSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_block();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region passive_wait */
	private void exitSequence_passive_wait() {
		switch (stateVector[2]) {
		case PASSIVE_WAIT_WAIT:
			exitSequence_passive_wait_wait();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region check */
	private void exitSequence_check() {
		switch (stateVector[3]) {
		case CHECK_CHECK:
			exitSequence_check_check();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_move__entry_Default() {
		enterSequence_move_robot_is_running_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_move_robot_is_running_R_gion___entry_Default() {
		enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1__entry_Default() {
		enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveFront_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle__entry_Default() {
		enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1__entry_Default() {
		enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_faceobject_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_move_robot_is_running_R_gion__robots_and_object_savePosition__entry_Default() {
		enterSequence_move_robot_is_running_R_gion__robots_and_object_savePosition_savePosition_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall__entry_Default() {
		enterSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_stop_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_passive_wait__entry_Default() {
		enterSequence_passive_wait_wait_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_check__entry_Default() {
		enterSequence_check_check_default();
	}
	
	private long react(long transitioned_before) {
		return transitioned_before;
	}
	
	private long move_robot_is_running_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robot_and_obstacle_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (robotIsBlocked) {
				exitSequence_move_robot_is_running_R_gion__robot_and_obstacle();
				enterSequence_move_robot_is_running_R_gion__blocage_default();
				move_robot_is_running_react(0);
				
				transitioned_after = 0;
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (thereIsAnObstacle) {
				exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning();
				enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveBack_default();
				move_robot_is_running_R_gion__robot_and_obstacle_react(0);
				
				transitioned_after = 0;
			} else {
				if (thereIsNoObstacle) {
					exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning();
					enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_default();
					move_robot_is_running_R_gion__robot_and_obstacle_react(0);
					
					transitioned_after = 0;
				}
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_R_gion__robot_and_obstacle_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (thereIsAGapDown) {
				exitSequence_move_robot_is_running_R_gion__robot_and_obstacle();
				raiseMoveBack();
				
				enterSequence_move_robot_is_running_R_gion__gap_down_default();
				move_robot_is_running_react(0);
				
				transitioned_after = 0;
			} else {
				if (thereIsAnObstacle) {
					exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves();
					enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning_default();
					move_robot_is_running_R_gion__robot_and_obstacle_react(0);
					
					transitioned_after = 0;
				} else {
					if (thereIsAnObjectFront) {
						exitSequence_move_robot_is_running_R_gion__robot_and_obstacle();
						raiseStop();
						
						enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_default();
						enterSequence_move_robot_is_running_R_gion__robots_and_object_savePosition_default();
						move_robot_is_running_react(0);
						
						transitioned_after = 0;
					} else {
						if (thereIsAVirtualWall) {
							exitSequence_move_robot_is_running_R_gion__robot_and_obstacle();
							enterSequence_move_robot_is_running_R_gion__virtualWall_default();
							move_robot_is_running_react(0);
							
							transitioned_after = 0;
						}
					}
				}
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_R_gion__robot_and_obstacle_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveBack_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (thereIsNoObstacleFront) {
				exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves();
				enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning_default();
				move_robot_is_running_R_gion__robot_and_obstacle_react(0);
				
				transitioned_after = 0;
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveFront_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (thereIsAFrontObstacle) {
				exitSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveFront();
				enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_r1_moveBack_default();
				move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_react(0);
				
				transitioned_after = 0;
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__gap_down_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (thereIsAGapDown) {
				exitSequence_move_robot_is_running_R_gion__gap_down();
				enterSequence_move_robot_is_running_R_gion__gap_down_default();
				move_robot_is_running_react(0);
				
				transitioned_after = 0;
			} else {
				if (thereIsnoGap) {
					exitSequence_move_robot_is_running_R_gion__gap_down();
					enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_turning_default();
					move_robot_is_running_react(0);
					
					transitioned_after = 0;
				}
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robots_and_object_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robots_and_object_r1_grip_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_moveBack_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (theGripIsClose) {
				exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_moveBack();
				enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_grip_default();
				move_robot_is_running_R_gion__robots_and_object_r1_grip_react(0);
				
				transitioned_after = 0;
			} else {
				if (theGripIsNotClose) {
					exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_moveBack();
					enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_moveBack_default();
					move_robot_is_running_R_gion__robots_and_object_r1_grip_react(0);
					
					transitioned_after = 0;
				}
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_R_gion__robots_and_object_r1_grip_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_grip_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (timeEvents[0]) {
				exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_grip();
				enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_pause__default();
				move_robot_is_running_R_gion__robots_and_object_r1_grip_react(0);
				
				transitioned_after = 0;
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_R_gion__robots_and_object_r1_grip_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_pause__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (theObjectIsGrip) {
				exitSequence_move_robot_is_running_R_gion__robots_and_object();
				enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_default();
				move_robot_is_running_react(0);
				
				transitioned_after = 0;
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			if (timeEvents[1]) {
				raiseCheckGripping();
			}
			transitioned_after = move_robot_is_running_R_gion__robots_and_object_r1_grip_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_turnRound_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (theGripIsNotClose) {
				exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_turnRound();
				raiseStop();
				
				enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_moveBack_default();
				move_robot_is_running_R_gion__robots_and_object_r1_grip_react(0);
				
				transitioned_after = 0;
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_R_gion__robots_and_object_r1_grip_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_faceobject_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (isFacingTheObject) {
				exitSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_faceobject();
				enterSequence_move_robot_is_running_R_gion__robots_and_object_r1_grip_r1_turnRound_default();
				move_robot_is_running_R_gion__robots_and_object_r1_grip_react(0);
				
				transitioned_after = 0;
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_R_gion__robots_and_object_r1_grip_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__robots_and_object_savePosition_savePosition_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<1) {
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			if (theObjectIsGrip) {
				raiseSaveRobotPosition();
			}
			transitioned_after = move_robot_is_running_R_gion__robots_and_object_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__blocage_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (thereIsNoObstacle) {
				exitSequence_move_robot_is_running_R_gion__blocage();
				enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_default();
				move_robot_is_running_react(0);
				
				transitioned_after = 0;
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__virtualWall_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (thereIsNoVirtualWall) {
				exitSequence_move_robot_is_running_R_gion__virtualWall();
				enterSequence_move_robot_is_running_R_gion__robot_and_obstacle_dodgeObstacle_moves_default();
				move_robot_is_running_react(0);
				
				transitioned_after = 0;
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_stop_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (thereIsAVirtualWall) {
				exitSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_stop();
				enterSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_block_default();
				move_robot_is_running_R_gion__virtualWall_react(0);
				
				transitioned_after = 0;
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_R_gion__virtualWall_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_block_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0) {
			if (thereIsAVirtualWall) {
				exitSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_block();
				enterSequence_move_robot_is_running_R_gion__virtualWall_do_not_cross_a_virtual_wall_virtual_stop_default();
				move_robot_is_running_R_gion__virtualWall_react(0);
				
				transitioned_after = 0;
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = move_robot_is_running_R_gion__virtualWall_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long passive_wait_wait_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<2) {
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			if (timeEvents[2]) {
				raiseDoPW();
			}
		}
		return transitioned_after;
	}
	
	private long check_check_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<3) {
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			if (timeEvents[3]) {
				raiseCheck();
			}
			transitioned_after = react(transitioned_before);
		}
		return transitioned_after;
	}
	
}
